services:
  - type: web
    name: power-view
    runtime: python
    region: singapore
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn powerview.wsgi:application --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: powerview.settings
      - key: DEBUG
        value: "False"
